# Generated by Django 4.0.2 on 2022-02-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_upvote_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default='somecontent', max_length=528, verbose_name='Content'),
            preserve_default=False,
        ),
    ]
