# Generated by Django 4.0.2 on 2022-02-19 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',)},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_response_time',
            new_name='last_request_time',
        ),
    ]
